name: File Audit

on: [pull_request, push]

jobs:
  file_audit_job:
    runs-on: ubuntu-22.04 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with: 
        submodules: recursive

    - name: Get Changes
      uses: jitterbit/get-changed-files@v1
      id : c
      with:
        format: space-delimited
    - name: File Audit
      uses: Weike-Gaming/file-audit@83d5b20620795b67d1e8c70a59abdeb4a44857ee
      with:
        github-output: "${{ steps.c.outputs.all }}"
        files-to-check: "Test.png DummyFile.txt"
