name: File Audit

on: [pull_request, push]

jobs:
  file_audit_job:
    runs-on: ubuntu-22.04 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      id : c
      with:
        format: space-delimited
        submodules: recursive
    - name: File Audit
      uses: Weike-Gaming/file-audit@40edf1d40418ee22d212bc414474f2603979ecad
      with:
        github-output: steps.abc.outputs
        files-to-check: "AM_Mixer"
